CREATE TABLE IF NOT EXISTS Manufacturer (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(256),
  nationality VARCHAR(256)
);


CREATE TABLE IF NOT EXISTS Beer (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(256),
  graduation REAL,
  "TYPE" VARCHAR(256),
  description VARCHAR(256),
  manufacturerid INTEGER,
  FOREIGN KEY(manufacturerid) REFERENCES manufacturer(id) ON DELETE CASCADE
);



